const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"公告",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"兼职",
                        "menuJump":"列表",
                        "tableName":"jianzhi"
                    }
                ],
                "menu":"兼职"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"兼职收藏",
                        "menuJump":"列表",
                        "tableName":"jianzhiCollection"
                    }
                ],
                "menu":"兼职收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"兼职留言",
                        "menuJump":"列表",
                        "tableName":"jianzhiLiuyan"
                    }
                ],
                "menu":"兼职留言"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-order",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"兼职申请",
                        "menuJump":"列表",
                        "tableName":"jianzhiOrder"
                    }
                ],
                "menu":"兼职申请"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
